CREATE TABLE PROJECT (
  PROJECT_ID       INTEGER     NOT NULL,
  CAPTION          VARCHAR(50) NOT NULL,
  ORGANIZATION_ID  INTEGER  
);


ALTER TABLE PROJECT
  ADD CONSTRAINT PROJECT_PK
      PRIMARY KEY (PROJECT_ID);



CREATE TABLE CATEGORY (
  CATEGORY_ID       INTEGER       NOT NULL,
  PARENT_ID         INTEGER,
  CAPTION           VARCHAR(100)  NOT NULL,
  CAT_INDEX         VARCHAR(2)    NOT NULL,
  DETAILS           VARCHAR(200),
  UNIT              VARCHAR(20),
  CAT_LEVEL         TINYINT       NOT NULL,
  TREE_CODE         VARCHAR(20)   NOT NULL,
  MAIN_FLAG         CHAR(1)       NOT NULL
);

ALTER TABLE CATEGORY
  ADD CONSTRAINT CATEGORY_PK
      PRIMARY KEY (CATEGORY_ID);



CREATE TABLE SUBCONTRACTOR (
  SUBCONTRACTOR_ID  INTEGER     NOT NULL,
  CAPTION           VARCHAR(50) NOT NULL
);


ALTER TABLE SUBCONTRACTOR
  ADD CONSTRAINT SUBCONTRACTOR_PK
      PRIMARY KEY (SUBCONTRACTOR_ID);



CREATE TABLE WORKER (
  WORKER_ID          INTEGER     NOT NULL,
  CAPTION            VARCHAR(50) NOT NULL,
  PERSON_ID          INTEGER  ,
  SUBCONTRACTOR_ID   INTEGER  
);

ALTER TABLE WORKER
  ADD CONSTRAINT WORKER_PK
      PRIMARY KEY (WORKER_ID);

ALTER TABLE WORKER
  ADD CONSTRAINT WORKER_FK1
      FOREIGN KEY (SUBCONTRACTOR_ID)
      REFERENCES SUBCONTRACTOR (SUBCONTRACTOR_ID);

ALTER TABLE WORKER
  ADD CONSTRAINT WORKER_CK1
      CHECK ( (PERSON_ID IS NULL AND SUBCONTRACTOR_ID IS NOT NULL) OR (PERSON_ID IS NOT NULL AND SUBCONTRACTOR_ID IS NULL) );



CREATE TABLE PROJECT_TEAM (
  PROJECT_ID    INTEGER       NOT NULL,
  TEAM_ID       INTEGER       NOT NULL,
  CAPTION       VARCHAR(50)   NOT NULL,
  BEG_DATE      DATE,
  END_DATE      DATE
);

ALTER TABLE PROJECT_TEAM
  ADD CONSTRAINT PROJECT_TEAM_PK
      PRIMARY KEY (PROJECT_ID, TEAM_ID);

ALTER TABLE PROJECT_TEAM
  ADD CONSTRAINT PROJECT_TEAM_FK1
      FOREIGN KEY (PROJECT_ID)
      REFERENCES PROJECT (PROJECT_ID);



CREATE TABLE PROJECT_TEAM_PERSON (
  PROJECT_ID    INTEGER   NOT NULL,
  TEAM_ID       INTEGER   NOT NULL,
  WORKER_ID     INTEGER   NOT NULL,
  TEAM_LEAD     CHAR(1)   DEFAULT '-' NOT NULL
);

ALTER TABLE PROJECT_TEAM_PERSON
  ADD CONSTRAINT PROJECT_TEAM_PERSON_PK
      PRIMARY KEY (PROJECT_ID, TEAM_ID, WORKER_ID);

ALTER TABLE PROJECT_TEAM_PERSON
  ADD CONSTRAINT PROJECT_TEAM_PERSON_FK1
      FOREIGN KEY (PROJECT_ID, TEAM_ID)
      REFERENCES PROJECT_TEAM (PROJECT_ID, TEAM_ID);

ALTER TABLE PROJECT_TEAM_PERSON
  ADD CONSTRAINT PROJECT_TEAM_PERSON_FK2
      FOREIGN KEY (WORKER_ID)
      REFERENCES WORKER (WORKER_ID);



CREATE TABLE PROJECT_WBS (
  PROJECT_ID       INTEGER      NOT NULL,
  CATEGORY_ID      INTEGER      NOT NULL,
  UNIT             CHAR(3)      NOT NULL,
  METRIC           DECIMAL(8,2) NOT NULL,
  WORKFORCE        DECIMAL(8,2) NOT NULL,
  PUP_METRIC       DECIMAL(8,2),
  PUP_WORKFORCE    DECIMAL(8,2)
);

ALTER TABLE PROJECT_WBS
  ADD CONSTRAINT PROJECT_WBS_PK
      PRIMARY KEY (PROJECT_ID, CATEGORY_ID);

ALTER TABLE PROJECT_WBS
  ADD CONSTRAINT PROJECT_WBS_FK1
      FOREIGN KEY (PROJECT_ID)
      REFERENCES PROJECT (PROJECT_ID);

ALTER TABLE PROJECT_WBS
  ADD CONSTRAINT PROJECT_WBS_FK2
      FOREIGN KEY (CATEGORY_ID)
      REFERENCES CATEGORY (CATEGORY_ID);



CREATE TABLE PROJECT_WBS_MANHOUR (
  PROJECT_ID       INTEGER      NOT NULL,
  CATEGORY_ID      INTEGER      NOT NULL,
  TEAM_ID          INTEGER      NOT NULL,
  WORKER_ID        INTEGER      NOT NULL,
  ACTIVITY_DATE    TIMESTAMP    NOT NULL,
  MANHOUR          TINYINT      NOT NULL,
  OVERTIME         TINYINT,
  LOCAL_MH         TINYINT,
  FOREIGN_MH       TINYINT,
  TR_MH            TINYINT
);

ALTER TABLE PROJECT_WBS_MANHOUR
  ADD CONSTRAINT PROJECT_WBS_MANHOUR_PK
      PRIMARY KEY (PROJECT_ID, CATEGORY_ID, TEAM_ID, WORKER_ID, ACTIVITY_DATE);

ALTER TABLE PROJECT_WBS_MANHOUR
  ADD CONSTRAINT PROJECT_WBS_MANHOUR_FK1
      FOREIGN KEY (PROJECT_ID, CATEGORY_ID)
      REFERENCES PROJECT_WBS (PROJECT_ID, CATEGORY_ID);

ALTER TABLE PROJECT_WBS_MANHOUR
  ADD CONSTRAINT PROJECT_WBS_MANHOUR_FK2
      FOREIGN KEY (PROJECT_ID, TEAM_ID, WORKER_ID)
      REFERENCES PROJECT_TEAM_PERSON (PROJECT_ID, TEAM_ID, WORKER_ID);



CREATE TABLE PROJECT_WBS_QUANTITY (
  PROJECT_ID        INTEGER      NOT NULL,
  CATEGORY_ID       INTEGER      NOT NULL,
  YEAR              SMALLINT     NOT NULL,
  TERM_TYPE         CHAR(1)      NOT NULL,
  TERM_ID           SMALLINT     NOT NULL,
  QUANTITY          DECIMAL(8,2) NOT NULL,
  IS_SUBCONTRACTOR  CHAR(1)      DEFAULT '-' NOT NULL
);

ALTER TABLE PROJECT_WBS_QUANTITY
  ADD CONSTRAINT PROJECT_WBS_QUANTITY_PK
      PRIMARY KEY (PROJECT_ID, CATEGORY_ID, YEAR, TERM_TYPE, TERM_ID);

ALTER TABLE PROJECT_WBS_QUANTITY
  ADD CONSTRAINT PROJECT_WBS_QUANTITY_FK
      FOREIGN KEY (PROJECT_ID, CATEGORY_ID)
      REFERENCES PROJECT_WBS (PROJECT_ID, CATEGORY_ID);

INSERT INTO USER_ACCOUNT (USERNAME,PASSWORD,CAPTION,STATUS) VALUES ('MHADMIN', '1', 'MANHOUR ADMIN', 'A');

INSERT INTO AUTHORITY_GROUP (AUTHORITY_GROUP,CAPTION) VALUES ('MANHOURADMIN', 'MANHOURADMIN');

INSERT INTO USER_AUTHORIZATION (USERNAME,AUTHORITY_GROUP) VALUES ('MHADMIN', 'MANHOURADMIN');
INSERT INTO USER_AUTHORIZATION (USERNAME,AUTHORITY_GROUP) VALUES ('MUSTAFA', 'MANHOURADMIN');

INSERT INTO MAIN_MENU (MENU, CAPTION, ICON, DISPLAY_ORDER) VALUES ('MANHOUR',  'MANHOUR', 'manhour.png', 1000);

INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('PROJECT',       'PROJECT',       'project.png',       'project/list',       'MANHOUR',  10);
INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('CATEGORY',      'CATEGORY',      'wbs.png',           'category/list',      'MANHOUR',  20);
INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('SUBCONTRACTOR', 'SUBCONTRACTOR', 'subcontractor.png', 'subcontractor/list', 'MANHOUR',  30);
INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('PROJECT_TEAM',  'PROJECT_TEAM',  'projectteam.png',   'projectTeam/list',   'MANHOUR',  40);
INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('PROJECT_WBS',   'PROJECT_WBS',   'wbs.png',           'projectWbs/list',    'MANHOUR',  50);
INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('REPORT',        'REPORT',        'report.png',        'report/list',        'MANHOUR',  60);

INSERT INTO PAGE_AUTHORIZATION (AUTHORITY_GROUP,PAGENAME) VALUES ('MANHOURADMIN', 'PROJECT');
INSERT INTO PAGE_AUTHORIZATION (AUTHORITY_GROUP,PAGENAME) VALUES ('MANHOURADMIN', 'CATEGORY');
INSERT INTO PAGE_AUTHORIZATION (AUTHORITY_GROUP,PAGENAME) VALUES ('MANHOURADMIN', 'SUBCONTRACTOR');
INSERT INTO PAGE_AUTHORIZATION (AUTHORITY_GROUP,PAGENAME) VALUES ('MANHOURADMIN', 'PROJECT_TEAM');
INSERT INTO PAGE_AUTHORIZATION (AUTHORITY_GROUP,PAGENAME) VALUES ('MANHOURADMIN', 'PROJECT_WBS');
INSERT INTO PAGE_AUTHORIZATION (AUTHORITY_GROUP,PAGENAME) VALUES ('MANHOURADMIN', 'REPORT');

INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'PROJECT',              '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'CATEGORY',             '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'SUBCONTRACTOR',        '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'WORKER',               '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'PROJECT_TEAM',         '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'PROJECT_TEAM_PERSON',  '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'PROJECT_WBS',          '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'PROJECT_WBS_MANHOUR',  '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'PROJECT_WBS_QUANTITY', '+', '+', '+', '+');

INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (1,NULL,'Mobilizasyon - Demobilizasyon Ýþleri','00',NULL,NULL,1,'00','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (14,1,'Mobilizasyon Ýþleri','05',NULL,'m2',2,'00-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (15,1,'Demobilizasyon Ýþleri','10',NULL,'m2',2,'00-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (2,NULL,'Destek Ýþleri ve Genel Hizmet Gruplarý','01','(sadece saat ücretli personel için)',NULL,1,'01','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (16,2,'Destek Ýþleri ve Genel Hizmet Gruplarý','05','(sadece saat ücretli personel için)',NULL,2,'01-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (130,16,'Teknik Emniyet iþleri','05','(iþ emniyeti personeli), (eðitimler dahil)','-',3,'01-05-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (131,16,'Güvenlik Ýþleri','10','(bekçiler)','-',3,'01-05-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (132,16,'Yemekhane Hizmetleri','15',NULL,'-',3,'01-05-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (133,16,'Kamp Bakým Ýþleri','20','(temizlik, tamirat, vb)','-',3,'01-05-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (134,16,'Þantiye Bakým Ýþleri','25','(temizlik, tamirat, vb)','-',3,'01-05-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (135,16,'Ambar Hizmetleri','30','(koltuk ambarlarý da dahil)','-',3,'01-05-30','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (136,16,'Tamir Bakým Atölyesi','35','(elektrik, araç vb)','-',3,'01-05-35','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (137,16,'Ulaþým Hizmetleri','40','(makam þöförleri, servis þöförleri vb)','-',3,'01-05-40','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (138,16,'Marangozhane Hizmetleri','45',NULL,'-',3,'01-05-45','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (139,16,'Beton Santralý','50',NULL,'-',3,'01-05-50','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (17,2,'Ölçüm Ýþleri','10','(sadece saat ücretli personel için)',NULL,2,'01-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (18,2,'Tahmil Tahliye Ýþleri','15','(yapým aþamasýna kadar olan taþýma, yükleme, boþaltma iþlemleri)',NULL,2,'01-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (140,18,'Ýskele malzemesi tahmil tahliye iþleri','05',NULL,'-',3,'01-15-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (141,18,'Ýnþaat malzemeleri tahmil tahliye iþleri','10',NULL,'-',3,'01-15-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (142,18,'Boru montajý tahmil tahliye iþleri','15',NULL,'-',3,'01-15-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (143,18,'Diðer tahmil tahliye iþleri','95',NULL,'-',3,'01-15-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (3,NULL,'Ýnþaat Ýþleri','02',NULL,NULL,1,'02','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (19,3,'Saha hazýrlama','05','(Saha temizlenmesi, Saha tesviyesi, Saha drenajý, vb)',NULL,2,'02-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (20,3,'Kazýk iþleri','10','(yapým, kazýk baþý kýrýlmasý, test, prefabrikasyon ve montaj iþleri dahil)',NULL,2,'02-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (144,20,'Çakma kazýk iþleri','05',NULL,'m',3,'02-10-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (145,20,'Fore kazýk iþleri','10',NULL,'m',3,'02-10-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (21,3,'Hafriyat iþleri','15','(Hafredilmiþ malzemenin saha dýþýna nakli dahil)',NULL,2,'02-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (22,3,'Dolgu iþleri','20','(Seçilmiþ malzemenin dolgu sahasýna nakli dahil)',NULL,2,'02-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (23,3,'Kalýp iþleri  (Çakýlmasý, Yaðlama, Sökümü)','25',NULL,NULL,2,'02-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (146,23,'Temel ve Zemin kalýplarý','05',NULL,'m2',3,'02-25-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (147,23,'Ekipman Temeli Kalýplarý','10',NULL,'m2',3,'02-25-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (148,23,'Üstyapý Kalýplarý','15',NULL,'m2',3,'02-25-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (149,23,'Diðer Kalýp Ýþleri','20',NULL,'m2',3,'02-25-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (150,23,'Kalýp iskelesi kurulmasý ve sökülmesi','25',NULL,'m3',3,'02-25-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (24,3,'Demir iþleri','30','(hasýr çelik iþleri dahil)',NULL,2,'02-30','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (151,24,'Demir Donatý Ýmalat Ýþleri','05','(kesme, bükme, prefabrikasyon, vb)','kg',3,'02-30-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (152,24,'Temel ve Zemin Döþeme Demirleri','10',NULL,'kg',3,'02-30-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (153,24,'Ekipman Temeli Demirleri','15',NULL,'kg',3,'02-30-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (154,24,'Üstyapý Demirleri','20',NULL,'kg',3,'02-30-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (155,24,'Diðer demir iþleri','25',NULL,'kg',3,'02-30-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (25,3,'Beton döküm iþleri','35','(Prekast ve saha betonu iþleri hariç), (beton dökümüne mastar veya perdah makinasý ile yüzey düzeltilmesi dahildir)',NULL,2,'02-35','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (156,25,'Grobeton','05',NULL,'m3',3,'02-35-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (157,25,'Temel ve Zemin Betonu Dökülmesi','10',NULL,'m3',3,'02-35-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (158,25,'Üstyapý Betonu','15',NULL,'m3',3,'02-35-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (159,25,'Ekipman Temeli Betonu','20',NULL,'m3',3,'02-35-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (160,25,'Grout','25',NULL,'m3',3,'02-35-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (161,25,'Þap betonu','30','(eðim betonu dahil)','m2',3,'02-35-30','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (162,25,'Beton yüzeylerde tamirat ve temizlik iþleri','35',NULL,'m3',3,'02-35-35','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (163,25,'Beton Koruma iþleri','40','(beton yüzeyinin sertleþmesi için iklime göre ýsýtma veya sulama vb)','-',3,'02-35-40','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (26,3,'Saha kaplamalarý, çevre düzenleme ve yollar','40',NULL,NULL,2,'02-40','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (164,26,'Saha betonu iþleri','05','(tasviye, kalýp, demir dahil)','m2',3,'02-40-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (165,26,'Yüzey kaplanmasý iþleri','10','(karo vb)','m2',3,'02-40-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (166,26,'Yol yapýmý','15',NULL,'m2',3,'02-40-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (167,26,'Bordür döþenmesi','20',NULL,'m',3,'02-40-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (168,26,'Çevre Çiti','25',NULL,'m',3,'02-40-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (169,26,'Çevre Duvarý','30',NULL,'m3',3,'02-40-30','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (170,26,'Yeþillendirme','35','(çim)','m2',3,'02-40-35','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (171,26,'Diðer Çevre düzenleme iþleri','95',NULL,'-',3,'02-40-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (27,3,'Gömülü eleman-ankraj iþleri','45',NULL,'kg',2,'02-45','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (28,3,'Prekast beton imalatlar','50','(kalýp, demir dahil)','m3',2,'02-50','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (29,3,'Yangýn koruma betonlarý','55',NULL,NULL,2,'02-55','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (172,29,'Çelik yüzeylerine yangýn koruma betonu tatbikatý','05',NULL,'m2',3,'02-55-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (173,29,'Ekipmanlarda yangýn koruma betonu tatbikatý','10',NULL,'m2',3,'02-55-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (174,29,'Diðer Yangýn Koruma Beton iþleri','95',NULL,'-',3,'02-55-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (30,3,'Çatý - Cephe kaplama iþleri','60',NULL,NULL,2,'02-60','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (175,30,'Çatý kaplama iþleri','05','(Yaðmur dereleri ve drenaj borularý dahil)','m2',3,'02-60-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (176,30,'Cephe kaplama iþleri','10',NULL,'m2',3,'02-60-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (177,30,'Yaðmur dereleri ve drenaj borularý montajý','15',NULL,'m',3,'02-60-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (178,30,'Ýzolasyon iþleri','20','(ýsý, su)','m2',3,'02-60-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (179,30,'Cephe boyasý','25',NULL,'m2',3,'02-60-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (180,30,'Diðer Çatý - Cephe kaplama iþleri','96',NULL,'-',3,'02-60-96','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (31,3,'Bina Ýnce Ýþleri','65',NULL,NULL,2,'02-65','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (181,31,'Su izolasyonu','03','(ýslak mekanlar için)','m2',3,'02-65-03','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (182,31,'Tuðla duvar iþleri','06',NULL,'m2',3,'02-65-06','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (183,31,'Alçýpan duvar iþleri','09','(ankrajlar dahil)','m2',3,'02-65-09','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (184,31,'Kaba sýva iþleri','12',NULL,'m2',3,'02-65-12','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (185,31,'Ýnce sýva iþleri','15',NULL,'m2',3,'02-65-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (186,31,'Alçý sýva iþleri','18',NULL,'m2',3,'02-65-18','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (187,31,'Asma tavan iþleri','21','(ankrajlar dahil)','m2',3,'02-65-21','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (188,31,'Terrazzo yer kaplama iþleri','24','(süpürgelik dahil)','m2',3,'02-65-24','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (189,31,'Seramik yer kaplama iþleri','27','(süpürgelik dahil)','m2',3,'02-65-27','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (190,31,'Mermer yer kaplama iþleri','30','(süpürgelik dahil)','m2',3,'02-65-30','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (191,31,'PVC esaslý yer kaplama iþleri','33','(linoleum vb, süpürgelik dahil)','m2',3,'02-65-33','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (192,31,'Epoxy bazlý yer kaplama iþleri','36',NULL,'m2',3,'02-65-36','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (193,31,'Parke yer kaplama iþleri','39','(süpürgelik dahil)','m2',3,'02-65-39','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (194,31,'Halý yer kaplama iþleri','42','(süpürgelik dahil)','m2',3,'02-65-42','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (195,31,'Yükseltilmiþ Döþeme iþleri','45',NULL,'m2',3,'02-65-45','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (196,31,'Seramik duvar kaplama iþleri','48','(ankrajlar dahil)','m2',3,'02-65-48','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (197,31,'Mermer duvar kaplama iþleri','51','(ankrajlar dahil)','m2',3,'02-65-51','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (198,31,'Granit duvar kaplama iþleri','54','(ankrajlar dahil)','m2',3,'02-65-54','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (199,31,'Duvar kaðýdý iþleri','57',NULL,'m2',3,'02-65-57','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (200,31,'Boya iþleri','60',NULL,'m2',3,'02-65-60','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (201,31,'Kartonpiyer iþleri','63','(metretül bazýnda alçýpan iþleri dahil)','m',3,'02-65-63','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (202,31,'Kapý iþleri','66','(kasalar, kanatlar, aksesuarlar dahil)','adet',3,'02-65-66','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (203,31,'Pencere Ýþleri','69','(kör kasa, kasa, kanat, aksesuarlar dahil)','m2, adet',3,'02-65-69','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (204,31,'Mobilya montajý','72',NULL,'m2',3,'02-65-72','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (205,31,'Çeþitli ekipman montajý (mutfak, çamaþýrhane vb)','75',NULL,'adet',3,'02-65-75','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (206,31,'Aksesuar montajý','78','(posta kutusu, kapý no. su, duþ perdesi vb)','adet',3,'02-65-78','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (207,31,'Bitmiþ imalatlarýn korunmasý iþleri','81',NULL,'-',3,'02-65-81','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (208,31,'Temizlik iþleri','84',NULL,'-',3,'02-65-84','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (32,3,'Bina içi elektro-mekanik tesisat iþleri','70',NULL,NULL,2,'02-70','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (209,32,'Tesisat için beton kýrýmý ve tamiri','05',NULL,'-',3,'02-70-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (210,32,'Pis su, temiz su tesisat iþleri','10',NULL,'m',3,'02-70-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (211,32,'Vitrifiye malzeme ve aksesuar montajý','15',NULL,'adet',3,'02-70-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (212,32,'Konduit döþenmesi','20',NULL,'m',3,'02-70-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (213,32,'Kablo tavasý montajý','25',NULL,'m',3,'02-70-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (214,32,'Elektrik ve aydýnlatma kablosu çekilmesi','30',NULL,'m',3,'02-70-30','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (215,32,'Buat, priz, aydýnlatma armatürü vb tesisat iþleri ve montajý','35',NULL,'adet',3,'02-70-35','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (216,32,'Telefon, anons vb haberleþme tesisat iþleri ve montajý','40',NULL,'adet',3,'02-70-40','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (217,32,'Bilgisayar, network ve merkezi anten sistemleri tesisat iþleri','45',NULL,'adet',3,'02-70-45','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (218,32,'Gaz alarmý sistemi tesisat iþleri','50',NULL,'adet',3,'02-70-50','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (219,32,'Yangýn ihbar tesisat iþleri','55',NULL,'adet',3,'02-70-55','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (220,32,'Yangýn söndürme tesisat iþleri','60',NULL,'m',3,'02-70-60','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (221,32,'Sýcak sulu sistem ýsýtma tesisatý iþleri','65',NULL,'m',3,'02-70-65','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (222,32,'HVAC sistemi montaj iþleri','70',NULL,'m',3,'02-70-70','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (223,32,'Bina otomasyon sistemi iþleri','75',NULL,'adet',3,'02-70-75','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (224,32,'Uydu ve Kapalý Devre TV sistemi iþleri','80',NULL,'adet',3,'02-70-80','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (225,32,'Bina içi ýsý izolasyon iþleri','85','(HVAC kanallarý hariç)','m',3,'02-70-85','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (33,3,'Ýskele kurulmasý, sökümü iþleri','75','(kalýp iskelesi hariç)',NULL,2,'02-75','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (34,3,'Testler','80','(sadece saat ücretli personel için), (Sýkýþtýrma testleri, Beton testleri, Elek analiz testleri)',NULL,2,'02-80','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (35,3,'Diðer inþaat iþleri','95',NULL,NULL,2,'02-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (226,35,'Saha temizlik iþleri','05',NULL,'-',3,'02-95-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (227,35,'Revizyon iþleri','10','(iþverenden/ana müteahhitten kaynaklanan)','-',3,'02-95-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (228,35,'Diðer inþaat iþleri','95',NULL,'-',3,'02-95-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (4,NULL,'Çelik Esaslý Saha Ýmalatlarý Ýþleri','03','(tahmil tahliye dahil)',NULL,1,'03','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (36,4,'Saha imalatlarý','05',NULL,NULL,2,'03-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (229,36,'Çelik konstrüksiyon imalatý','05',NULL,'kg',3,'03-05-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (230,36,'Hafif Çelik imalatý','10',NULL,'kg',3,'03-05-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (231,36,'Boru mesnetleri, support (boru, kablo tavasý vb) imalatý','15',NULL,'kg',3,'03-05-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (232,36,'Tank imalatý','20','(tank taban, duvar ve çatý vb)','kg',3,'03-05-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (233,36,'Çelik ve saç imalatlarý kaynak iþleri','25',NULL,'-',3,'03-05-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (234,36,'Diðer saha imalatlarý','90',NULL,'kg',3,'03-05-90','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (235,36,'Revizyon iþleri','95','(iþverenden/ana müteahhitten kaynaklanan)','-',3,'03-05-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (5,NULL,'Çelik Montajý Ýþleri','04',NULL,NULL,1,'04','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (37,5,'Çelik Montajý Ýþleri','05',NULL,NULL,2,'04-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (236,37,'Bina ana çelikleri montajý - Hafif','05','(20 kg/m ve altý) - projesine göre deðiþebilir','kg',3,'04-05-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (237,37,'Bina ana çelikleri montajý - Orta','10','(21 kg/m ve 79 kg/m arasý) - projesine göre deðiþebilir','kg',3,'04-05-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (238,37,'Bina ana çelikleri montajý - Aðýr','15','(80 kg/m ve üstü) - projesine göre deðiþebilir','kg',3,'04-05-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (239,37,'Yapý çelikleri montajý - Hafif','20','(20 kg/m ve altý) - projesine göre deðiþebilir','kg',3,'04-05-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (240,37,'Yapý çelikleri montajý - Orta','25','(21 kg/m ve 79 kg/m arasý) - projesine göre deðiþebilir','kg',3,'04-05-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (241,37,'Yapý çelikleri montajý - Aðýr','30','(80 kg/m ve üstü) - projesine göre deðiþebilir','kg',3,'04-05-30','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (242,37,'Boru köprüleri çelik montajý','35',NULL,'kg',3,'04-05-35','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (243,37,'Þimleme iþleri','40',NULL,'kg',3,'04-05-40','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (244,37,'Çelik Montajý Kaynak iþleri','45',NULL,'-',3,'04-05-45','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (245,37,'Diðer Çelik Montajý iþleri','90',NULL,'kg',3,'04-05-90','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (6,NULL,'Ekipman Montajý Ýþleri','05',NULL,NULL,1,'05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (38,6,'Kolonlar','03',NULL,'kg',2,'05-03','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (39,6,'Drumlar','06',NULL,'kg',2,'05-06','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (40,6,'Reaktör - Rejeneratör','09',NULL,'kg',2,'05-09','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (41,6,'Fýrýnlar (furnace)','12',NULL,'kg',2,'05-12','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (42,6,'Çelik Bacalar','15',NULL,'kg',2,'05-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (43,6,'Silindirik saha tanklarý','18',NULL,'kg',2,'05-18','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (44,6,'Basýnçlý Saha tanklarý (küresel vb)','21',NULL,'kg',2,'05-21','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (45,6,'Döner fýrýnlar','24',NULL,'kg',2,'05-24','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (46,6,'Pompalar - kompresörler','27',NULL,'kg',2,'05-27','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (47,6,'Türbin - jeneratörler','30',NULL,'kg',2,'05-30','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (48,6,'Fanlar','33',NULL,NULL,2,'05-33','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (49,6,'Air Coolerlar','36',NULL,NULL,2,'05-36','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (50,6,'Kýrýcýlar','39',NULL,NULL,2,'05-39','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (51,6,'Deðirmenler','42',NULL,NULL,2,'05-42','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (52,6,'Eþanjörler','45',NULL,NULL,2,'05-45','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (53,6,'Soðutma kuleleri','48',NULL,NULL,2,'05-48','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (54,6,'Silolar ve silo ekipmanlarý','51',NULL,NULL,2,'05-51','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (55,6,'Siklonlar, Preheaterlar','54',NULL,NULL,2,'05-54','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (56,6,'Filtreler','57',NULL,NULL,2,'05-57','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (57,6,'Þutlar - gaz kanallarý','60',NULL,NULL,2,'05-60','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (58,6,'Konveyörler','63',NULL,NULL,2,'05-63','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (59,6,'Tavan vinçleri','66',NULL,NULL,2,'05-66','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (60,6,'Asansörler','69',NULL,NULL,2,'05-69','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (61,6,'Atýk ýsý kazaný','72',NULL,NULL,2,'05-72','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (62,6,'Endüstriyel buhar kazaný','75',NULL,NULL,2,'05-75','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (63,6,'Paket ekipmanlar','78','(ekipman montajý kodlarýnda yer almayan diðer ekipmanlar)',NULL,2,'05-78','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (64,6,'Diðer Ekipman Montaj Ýþleri','95',NULL,NULL,2,'05-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (7,NULL,'Boru Ýmalat Ýþleri','06','(imalat atelyesi sahasý içerisindeki tahmil tahliye iþleri, kesme, fitting dahil), (tüm yeraltý, yerüstü borularý için)',NULL,1,'06','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (65,7,'Karbon Çeliði Boru Ýmalat Ýþleri','05',NULL,NULL,2,'06-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (66,7,'Alaþýmlý Çelik Boru Ýmalat Ýþleri','10',NULL,NULL,2,'06-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (67,7,'Paslanmaz Çelik Boru Ýmalat Ýþleri','15',NULL,NULL,2,'06-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (68,7,'Diþli Baðlantýlý Boru Ýmalat Ýþleri','20',NULL,NULL,2,'06-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (69,7,'Ceketli Boru Ýmalat Ýþleri','25',NULL,NULL,2,'06-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (70,7,'Ýçten kaplamalý FRP (Fiberli plastik kompozit borular) Boru Ýmalat Ýþleri','30',NULL,NULL,2,'06-30','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (71,7,'Ýçten kaplamasýz FRP (Fiberli plastik kompozit borular) Boru Ýmalat Ýþleri','35',NULL,NULL,2,'06-35','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (72,7,'Kaplamalý borular (Beton, epoxy vb) Ýmalat Ýþleri','40',NULL,NULL,2,'06-40','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (73,7,'Diðer Boru Ýmalat Ýþleri','95',NULL,NULL,2,'06-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (8,NULL,'Yeraltý Boru Montaj Ýþleri','07',NULL,NULL,1,'07','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (74,8,'Beton boru montajý','05',NULL,'kg, m',2,'07-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (75,8,'PVC ve PE Boru montajý','10','(tüm çaplar)',NULL,2,'07-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (76,8,'Döküm veya çelik boru montajý','15',NULL,NULL,2,'07-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (77,8,'Diðer Boru Ýmalat Ýþleri','95',NULL,NULL,2,'07-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (9,NULL,'Yerüstü Boru Montaj Ýþleri','08','(tahmil tahliye, kesme, fitting iþleri dahil)',NULL,1,'08','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (78,9,'Karbon Çeliði Boru Montaj Ýþleri','05',NULL,NULL,2,'08-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (79,9,'Alaþýmlý Çelik Boru montaj Ýþleri','10',NULL,NULL,2,'08-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (80,9,'Paslanmaz Çelik Boru montaj Ýþleri','15',NULL,NULL,2,'08-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (81,9,'Diþli Baðlantýlý Boru montaj Ýþleri','20',NULL,NULL,2,'08-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (82,9,'Ceketli Boru montaj Ýþleri','25',NULL,NULL,2,'08-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (83,9,'Ýçten kaplamalý FRP (Fiberli plastik kompozit borular) Boru montaj Ýþleri','30',NULL,NULL,2,'08-30','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (84,9,'Ýçten kaplamasýz FRP (Fiberli plastik kompozit borular) Boru montaj Ýþleri','35',NULL,NULL,2,'08-35','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (85,9,'Kaplamalý borular (Beton, epoxy vb) montaj Ýþleri','40',NULL,NULL,2,'08-40','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (86,9,'Tie-In Boru Baðlantýlarý','45',NULL,NULL,2,'08-45','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (87,9,'Vana Montajlarý','50',NULL,NULL,2,'08-50','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (88,9,'Refakat Hatlarý Ýmalat ve Montaj Ýþleri','55',NULL,'m, kg',2,'08-55','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (89,9,'Boru Demontaj Ýþleri','60',NULL,NULL,2,'08-60','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (90,9,'Isýl Ýþlem','65',NULL,'adet',2,'08-65','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (91,9,'Testler','70','(sadece saat ücretli personel için)',NULL,2,'08-70','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (92,9,'Diðer Non-ferrous borular','75',NULL,'kg',2,'08-75','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (93,9,'Diðer Yerüstü Boru Montaj Ýþleri','95',NULL,NULL,2,'08-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (10,NULL,'Ýzolasyon Ýþleri','09',NULL,NULL,1,'09','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (94,10,'Sýcak Ýzolasyon Ýþleri','05',NULL,NULL,2,'09-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (95,10,'Soðuk Ýzolasyon Ýþleri','10',NULL,NULL,2,'09-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (96,10,'Diðer Ýzolasyon Ýþleri','95',NULL,NULL,2,'09-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (11,NULL,'Boya ve Kaplama Ýþleri','10',NULL,NULL,1,'10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (97,11,'Yüzey Hazýrlama Ýþleri','05','(kuvars kumu, grid, tel fýrça, döner fýrça, vb)','m2, kg',2,'10-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (98,11,'Astar Boya Ýþleri','10',NULL,NULL,2,'10-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (99,11,'Son Kat Boya Ýþleri','15','(ara kat dahil)',NULL,2,'10-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (100,11,'Touch-up iþleri','20','(kaynak yerlerinin boyanmasý dahil)','m2, kg',2,'10-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (101,11,'Kaplama Ýþleri (coating works)','25',NULL,'m2',2,'10-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (102,11,'Diðer Boya ve Kaplama Ýþleri','95',NULL,NULL,2,'10-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (12,NULL,'Elektrik Montaj Ýþleri','11','(bina tesisatlarý hariç)',NULL,1,'11','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (103,12,'Kablo tavalarý / merdivenleri montajý','03','(kapaklarý dahil)','m, kg',2,'11-03','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (104,12,'Kablo Montajý','06',NULL,NULL,2,'11-06','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (105,12,'Kablo Baðlantýlarý','09','(gland, baþlýk, pabuç, vb)','adet',2,'11-09','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (106,12,'Yüksek Gerilim Ekipman Montajý','12',NULL,'adet',2,'11-12','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (107,12,'Orta Gerilim Ekipman Montajý','15',NULL,'adet',2,'11-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (108,12,'Alçak Gerilim Ekipman Montajý','18',NULL,'adet',2,'11-18','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (109,12,'Push Station montajý','21',NULL,'adet',2,'11-21','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (110,12,'Priz montajý','24',NULL,'adet',2,'11-24','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (111,12,'Topraklama Ýþleri','27','(testler vb dahil)','m',2,'11-27','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (112,12,'Katodik Koruma Ýþleri','30','(testler vb dahil)','adet, m',2,'11-30','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (113,12,'Aydýnlatma montajý','33',NULL,'adet, m',2,'11-33','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (114,12,'Yangýn ihbar sistemi montajý','36',NULL,'adet, m',2,'11-36','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (115,12,'Haberleþme sistemi montajý','39',NULL,'adet, m',2,'11-39','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (116,12,'Elektrikli Isýtma (heat tracing) Sistemi Montajý','42',NULL,'adet, m',2,'11-42','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (117,12,'Gaz Monitör Sistemi Montajý','45',NULL,'adet, m',2,'11-45','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (118,12,'Yýldýrýmdan Korunma Sistemi Montajý','48','(elektrod, iletken hatlar, testler vb dahil)','adet, m',2,'11-48','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (119,12,'Akü odalarý, UPS vb Montajý','51',NULL,'adet',2,'11-51','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (120,12,'Þalt Sahasý Montaj Ýþleri','54',NULL,'kg',2,'11-54','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (121,12,'Havai Hat Montajý','57',NULL,'adet, m',2,'11-57','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (122,12,'Diðer Elektrik Montaj Ýþleri','95',NULL,NULL,2,'11-95','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (13,NULL,'Enstrüman Montaj Ýþleri','12',NULL,NULL,1,'12','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (123,13,'Kablo tavalarý / merdivenleri montajý','05',NULL,'m, kg',2,'12-05','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (124,13,'Kablo Montajý','10',NULL,'m',2,'12-10','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (125,13,'Kablo Baðlantýlarý','15',NULL,'adet',2,'12-15','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (126,13,'Enstrümantasyon Borusu Montajý','20','(refakat hatlarý hariç, header ve mesnetler dahil)','m, kg',2,'12-20','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (127,13,'Enstrüman Kalibrasyon Ýþleri','25',NULL,'adet',2,'12-25','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (128,13,'Enstrüman Montaj Ýþleri','30',NULL,'adet',2,'12-30','+');
INSERT INTO CATEGORY (CATEGORY_ID,PARENT_ID,CAPTION,CAT_INDEX,DETAILS,UNIT,CAT_LEVEL,TREE_CODE,MAIN_FLAG) VALUES (129,13,'Diðer Enstrüman Montaj Ýþleri','95',NULL,NULL,2,'12-95','+');
