SPOOL D:\manhour.log

PROMPT "CREATE TABLE PROJECT"

CREATE TABLE PROJECT (
  PROJECT_ID       NUMBER(8)    NOT NULL,
  CAPTION          VARCHAR2(50) NOT NULL,
  ORGANIZATION_ID  NUMBER(8)
);


ALTER TABLE PROJECT
  ADD CONSTRAINT PROJECT_PK
      PRIMARY KEY (PROJECT_ID);

--ALTER TABLE PROJECT
--  ADD CONSTRAINT PROJECT_FK1
--      FOREIGN KEY (ORGANIZATION_ID)
--      REFERENCES APPS.XXGAMA_ADSA_ORGANIZATIONS_V (ORGANIZATION_ID);



PROMPT "CREATE TABLE CATEGORY"

CREATE TABLE CATEGORY (
  CATEGORY_ID       NUMBER(8)      NOT NULL,
  PARENT_ID         NUMBER(8),
  CAPTION           VARCHAR2(100)  NOT NULL,
  CAT_INDEX         VARCHAR2(2)    NOT NULL,
  DETAILS           VARCHAR2(250),
  UNIT              VARCHAR2(20),
  CAT_LEVEL         NUMBER(2)      NOT NULL,
  TREE_CODE         VARCHAR2(20)   NOT NULL,
  MAIN_FLAG         CHAR(1)        NOT NULL
);

INSERT INTO CATEGORY
SELECT DISTINCT
    CAT_HEADER_ID AS CATEGORY_ID,
    PARENT_ID,
    CATEGORY_DESCRIPTION AS CAPTION,
    CATEGORY_CODE AS CAT_INDEX,
    CATEGORY_DETAIL AS DETAILS,
    BIRIM AS UNIT,
    CAT_LEVEL,
    CONCAT_CATEGORY_CODE AS TREE_CODE,
    '+' AS MAIN_FLAG
  FROM APPS.XXGAMA_ADSA_WBS_CATEGORY_V
 WHERE (CAT_HEADER_ID, CAT_LEVEL) IN 
         (SELECT CAT_HEADER_ID, MAX(CAT_LEVEL)
            FROM APPS.XXGAMA_ADSA_WBS_CATEGORY_V
        GROUP BY CAT_HEADER_ID);


ALTER TABLE CATEGORY
  ADD CONSTRAINT CATEGORY_PK
      PRIMARY KEY (CATEGORY_ID);



PROMPT "CREATE TABLE SUBCONTRACTOR"

CREATE TABLE SUBCONTRACTOR (
  SUBCONTRACTOR_ID  NUMBER(8)    NOT NULL,
  CAPTION           VARCHAR2(50) NOT NULL
);


ALTER TABLE SUBCONTRACTOR
  ADD CONSTRAINT SUBCONTRACTOR_PK
      PRIMARY KEY (SUBCONTRACTOR_ID);



PROMPT "CREATE TABLE WORKER"

CREATE TABLE WORKER (
  WORKER_ID          NUMBER(8)    NOT NULL,
  CAPTION            VARCHAR2(50) NOT NULL,
  PERSON_ID          NUMBER(8),
  SUBCONTRACTOR_ID   NUMBER(8)
);

ALTER TABLE WORKER
  ADD CONSTRAINT WORKER_PK
      PRIMARY KEY (WORKER_ID);

ALTER TABLE WORKER
  ADD CONSTRAINT WORKER_FK1
      FOREIGN KEY (SUBCONTRACTOR_ID)
      REFERENCES SUBCONTRACTOR (SUBCONTRACTOR_ID);

--ALTER TABLE WORKER
--  ADD CONSTRAINT WORKER_FK2
--      FOREIGN KEY (PERSON_ID)
--      REFERENCES APPS.XXGAMA_ADSA_PERSONEL_V (PERSON_ID);

ALTER TABLE WORKER
  ADD CONSTRAINT WORKER_CK1
      CHECK ( (PERSON_ID IS NULL AND SUBCONTRACTOR_ID IS NOT NULL) OR (PERSON_ID IS NOT NULL AND SUBCONTRACTOR_ID IS NULL) );



PROMPT "CREATE TABLE PROJECT_TEAM"

CREATE TABLE PROJECT_TEAM (
  PROJECT_ID    NUMBER(8)     NOT NULL,
  TEAM_ID       NUMBER(8)     NOT NULL,
  CAPTION       VARCHAR2(50)  NOT NULL,
  BEG_DATE      DATE,
  END_DATE      DATE
);

ALTER TABLE PROJECT_TEAM
  ADD CONSTRAINT PROJECT_TEAM_PK
      PRIMARY KEY (PROJECT_ID, TEAM_ID);

ALTER TABLE PROJECT_TEAM
  ADD CONSTRAINT PROJECT_TEAM_FK1
      FOREIGN KEY (PROJECT_ID)
      REFERENCES PROJECT (PROJECT_ID);



PROMPT "CREATE TABLE PROJECT_TEAM_PERSON"

CREATE TABLE PROJECT_TEAM_PERSON (
  PROJECT_ID    NUMBER(8) NOT NULL,
  TEAM_ID       NUMBER(8) NOT NULL,
  WORKER_ID     NUMBER(8) NOT NULL,
  TEAM_LEAD     CHAR(1)   DEFAULT '-' NOT NULL
);

ALTER TABLE PROJECT_TEAM_PERSON
  ADD CONSTRAINT PROJECT_TEAM_PERSON_PK
      PRIMARY KEY (PROJECT_ID, TEAM_ID, WORKER_ID);

ALTER TABLE PROJECT_TEAM_PERSON
  ADD CONSTRAINT PROJECT_TEAM_PERSON_FK1
      FOREIGN KEY (PROJECT_ID, TEAM_ID)
      REFERENCES PROJECT_TEAM (PROJECT_ID, TEAM_ID);

ALTER TABLE PROJECT_TEAM_PERSON
  ADD CONSTRAINT PROJECT_TEAM_PERSON_FK2
      FOREIGN KEY (WORKER_ID)
      REFERENCES WORKER (WORKER_ID);



PROMPT "CREATE TABLE PROJECT_WBS"

CREATE TABLE PROJECT_WBS (
  PROJECT_ID       NUMBER(8)    NOT NULL,
  CATEGORY_ID      NUMBER(8)    NOT NULL,
  UNIT             CHAR(3)      NOT NULL,
  METRIC           NUMBER(8,2)  NOT NULL,
  WORKFORCE        NUMBER(8,2)  NOT NULL,
  PUP_METRIC       NUMBER(8,2),
  PUP_WORKFORCE    NUMBER(8,2)
);

ALTER TABLE PROJECT_WBS
  ADD CONSTRAINT PROJECT_WBS_PK
      PRIMARY KEY (PROJECT_ID, CATEGORY_ID);

ALTER TABLE PROJECT_WBS
  ADD CONSTRAINT PROJECT_WBS_FK1
      FOREIGN KEY (PROJECT_ID)
      REFERENCES PROJECT (PROJECT_ID);

ALTER TABLE PROJECT_WBS
  ADD CONSTRAINT PROJECT_WBS_FK2
      FOREIGN KEY (CATEGORY_ID)
      REFERENCES CATEGORY (CATEGORY_ID);



PROMPT "CREATE TABLE PROJECT_WBS_MANHOUR"

CREATE TABLE PROJECT_WBS_MANHOUR (
  PROJECT_ID       NUMBER(8)    NOT NULL,
  CATEGORY_ID      NUMBER(8)    NOT NULL,
  TEAM_ID          NUMBER(8)    NOT NULL,
  WORKER_ID        NUMBER(8)    NOT NULL,
  ACTIVITY_DATE    DATE         NOT NULL,
  MANHOUR          NUMBER(2)    NOT NULL,
  OVERTIME         NUMBER(2),
  LOCAL_MH         NUMBER(2),
  FOREIGN_MH       NUMBER(2),
  TR_MH            NUMBER(2)
);

ALTER TABLE PROJECT_WBS_MANHOUR
  ADD CONSTRAINT PROJECT_WBS_MANHOUR_PK
      PRIMARY KEY (PROJECT_ID, CATEGORY_ID, TEAM_ID, WORKER_ID, ACTIVITY_DATE);

ALTER TABLE PROJECT_WBS_MANHOUR
  ADD CONSTRAINT PROJECT_WBS_MANHOUR_FK1
      FOREIGN KEY (PROJECT_ID, CATEGORY_ID)
      REFERENCES PROJECT_WBS (PROJECT_ID, CATEGORY_ID);

ALTER TABLE PROJECT_WBS_MANHOUR
  ADD CONSTRAINT PROJECT_WBS_MANHOUR_FK2
      FOREIGN KEY (PROJECT_ID, TEAM_ID, WORKER_ID)
      REFERENCES PROJECT_TEAM_PERSON (PROJECT_ID, TEAM_ID, WORKER_ID);



PROMPT "CREATE TABLE PROJECT_WBS_QUANTITY"

CREATE TABLE PROJECT_WBS_QUANTITY (
  PROJECT_ID        NUMBER(8)    NOT NULL,
  CATEGORY_ID       NUMBER(8)    NOT NULL,
  YEAR              NUMBER(4)    NOT NULL,
  TERM_TYPE         CHAR(1)      NOT NULL,
  TERM_ID           NUMBER(4)    NOT NULL,
  QUANTITY          NUMBER(8,2)  NOT NULL,
  IS_SUBCONTRACTOR  CHAR(1)      DEFAULT '-' NOT NULL
);

ALTER TABLE PROJECT_WBS_QUANTITY
  ADD CONSTRAINT PROJECT_WBS_QUANTITY_PK
      PRIMARY KEY (PROJECT_ID, CATEGORY_ID, YEAR, TERM_TYPE, TERM_ID);

ALTER TABLE PROJECT_WBS_QUANTITY
  ADD CONSTRAINT PROJECT_WBS_QUANTITY_FK
      FOREIGN KEY (PROJECT_ID, CATEGORY_ID)
      REFERENCES PROJECT_WBS (PROJECT_ID, CATEGORY_ID);

INSERT INTO USER_ACCOUNT (USERNAME,PASSWORD,CAPTION,STATUS) VALUES ('MHADMIN', '1', 'MANHOUR ADMIN', 'A');

INSERT INTO AUTHORITY_GROUP (AUTHORITY_GROUP,CAPTION) VALUES ('MANHOURADMIN', 'MANHOURADMIN');

INSERT INTO USER_AUTHORIZATION (USERNAME,AUTHORITY_GROUP) VALUES ('MHADMIN', 'MANHOURADMIN');
INSERT INTO USER_AUTHORIZATION (USERNAME,AUTHORITY_GROUP) VALUES ('MUSTAFA', 'MANHOURADMIN');

INSERT INTO MAIN_MENU (MENU, CAPTION, ICON, DISPLAY_ORDER) VALUES ('MANHOUR',  'MANHOUR', 'manhour.png', 1000);

INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('PROJECT',       'PROJECT',       'project.png',       'project/list',       'MANHOUR',  10);
INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('CATEGORY',      'CATEGORY',      'wbs.png',           'category/list',      'MANHOUR',  20);
INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('SUBCONTRACTOR', 'SUBCONTRACTOR', 'subcontractor.png', 'subcontractor/list', 'MANHOUR',  30);
INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('PROJECT_TEAM',  'PROJECT_TEAM',  'projectteam.png',   'projectTeam/list',   'MANHOUR',  40);
INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('PROJECT_WBS',   'PROJECT_WBS',   'wbs.png',           'projectWbs/list',    'MANHOUR',  50);
INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('REPORT',        'REPORT',        'report.png',        'report/list',        'MANHOUR',  60);

INSERT INTO PAGE_AUTHORIZATION (AUTHORITY_GROUP,PAGENAME) VALUES ('MANHOURADMIN', 'PROJECT');
INSERT INTO PAGE_AUTHORIZATION (AUTHORITY_GROUP,PAGENAME) VALUES ('MANHOURADMIN', 'CATEGORY');
INSERT INTO PAGE_AUTHORIZATION (AUTHORITY_GROUP,PAGENAME) VALUES ('MANHOURADMIN', 'SUBCONTRACTOR');
INSERT INTO PAGE_AUTHORIZATION (AUTHORITY_GROUP,PAGENAME) VALUES ('MANHOURADMIN', 'PROJECT_TEAM');
INSERT INTO PAGE_AUTHORIZATION (AUTHORITY_GROUP,PAGENAME) VALUES ('MANHOURADMIN', 'PROJECT_WBS');
INSERT INTO PAGE_AUTHORIZATION (AUTHORITY_GROUP,PAGENAME) VALUES ('MANHOURADMIN', 'REPORT');

INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'PROJECT',              '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'CATEGORY',             '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'SUBCONTRACTOR',        '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'WORKER',               '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'PROJECT_TEAM',         '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'PROJECT_TEAM_PERSON',  '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'PROJECT_WBS',          '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'PROJECT_WBS_MANHOUR',  '+', '+', '+', '+');
INSERT INTO TABLE_AUTHORIZATION (AUTHORITY_GROUP,TABLENAME,ALLOW_SELECT,ALLOW_UPDATE,ALLOW_INSERT,ALLOW_DELETE) VALUES ('MANHOURADMIN', 'PROJECT_WBS_QUANTITY', '+', '+', '+', '+');

spool off
